config/routes.rb
Wedding::Application.routes.draw do

  resources :invitees do
    resources :guests
  end

resources :location, :hotels, :gifts, :pictures

  root "welcome#index"

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :invitee
end

app/models/invitee.rb
class Invitee < ActiveRecord::Base
	has_many :guests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :allow_iframe_requests

	def allow_iframe_requests
	  response.headers.delete('X-Frame-Options')
	end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
	
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  
  def create
    @invitee = Invitee.find(params[:invitee_id])
    @guest = @invitee.guests.create(guest_params)
    redirect_to invitee_path(@invitee)
  end

  def update
	@guest = Guests.find(params[:id])
	@invitee.guest.update(params[:guests].permit(:attend))
	#@guest.update
	redirect_to invitee_path
  end

 
  private
    def guest_params
      params.require(:guest).permit(:name, :attend)
    end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
	
end

app/controllers/invitees_controller.rb
class InviteesController < ApplicationController
	
	def new
	end

	def create
		#render :text => (params[:invitee])
		@invitee = Invitee.new(invitee_params)

		@invitee.save
		redirect_to @invitee
	end

	def show
		@invitee = Invitee.find(params[:id])
		@guests = @invitee.guests

	end

	def index
		@invitees = Invitee.all
	end

	def edit
	  @invitee = Invitee.find(params[:id])
	  #@invitee.guest.find(params[:invitee_id])
	end

	def update
	  @invitee = Invitee.find(params[:id])
	  @invitee.update(invitee_params)
	  redirect_to @invitee
	 end

	private
		def invitee_params
			params.require(:invitee).permit(:name, :option)
		end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
	
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
  def index
  d = Date.parse("31-10-2014")
  next_year = Date.today.year
  wed_day = "#{d.day}-#{d.month}-#{next_year}"
  @days = (Date.parse(wed_day) - Date.today).to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/invitees_helper.rb
module InviteesHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hotels/index.html.erb
<%= stylesheet_link_tag "hotels", media: "all", "data-turbolinks-track" => true %>

<table>
<th></th>
<tr>
	<td>
		<%= link_to image_tag('hotels/heerlijkheid.jpeg', class: "img-responsive", alt: "Heerlijkheid"), 'http://rubyonrails.org' %>
	</td>
</tr>
</table>

app/views/invitees/edit.html.erb
<h1>Editing Invitee</h1>
 
<%= form_for :invitee, url: invitee_path(@invitee), method: :patch do |f| %>

  <p>
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </p>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<h2>Voeg een gast toe</h2>
<%= form_for([@invitee, @invitee.guests.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :attend %><br>
    <%= f.text_area :attend %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

 
<%= link_to 'Back', invitees_path %>

app/views/invitees/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>Genodigden</h1>
  </div>
</div>


<div class="container">
	<table>
	  <tr>
	    <th>Id</th>
	    <th>Naam</th>
	  </tr>
	 
	  <% @invitees.each do |invitee| %>
	    <tr>
	      <td><%= invitee.id %></td>
	      <td><%= invitee.name %></td>
	      <td><%= link_to 'Show', invitee_path(invitee) %></td>
    	  <td><%= link_to 'Edit', edit_invitee_path(invitee) %></td>
	    </tr>
	  <% end %>
	</table>
</div>



<div class="container">
<%= link_to 'New article', new_invitee_path %>
</div>

app/views/invitees/new.html.erb
<div class="container">
  <div class="page-header">
    <h1>New Invitee</h1>
  </div>
</div>

<div class="container">
  <%= form_for :invitee, url: invitees_path do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
   
    <p>
      <%= f.submit 'Voeg toe'%>
    </p>
  <% end %>
</div>
<div class="container">
    <%= link_to 'Back', invitees_path %>
</div>

app/views/invitees/show.html.erb
<div class="page-header">
<h1>  <%= @invitee.name %></h1>
</div>



<div class='row'>
	<div class='col-sm-4'>
		<table class="table table-striped">
		<th>ID</th>
		<th>Naam</th>
		<th>Aanwezig <span class="glyphicon glyphicon-info-sign" data-toggle="modal" data-target="#myModal"> </span></th>
		<th>Edit</th>
		<% @invitee.guests.each do |guest| %>
			<tr>
			<td><%= guest.id %> </a></td>
			<td><%= guest.name %> </a></td>
				<td>
				<% if guest.attend == 1 %>
					<% btn_color = "btn btn-success" %>
					<% btn_color_dif = "btn btn-default"%>
					<% attending = "Ja"%>
					<% attending_dif = "Nee" %>
				<% else %>
					<% btn_color = "btn btn-warning" %>
					<% btn_color_dif = "btn btn-warning "%>
					<% attending = "Nee"%>
					<% attending_dif = "Ja" %>
				<% end %>
				<!-- Split button -->
				<div class="btn-group">
				  <button type="button" class="<%= btn_color %> dropdown-toggle" data-toggle="dropdown"><%= attending %>
				    <span class="caret"></span>
	
				  </button>
				  <ul class="dropdown-menu" role="menu">
				    <li><a href="/pages/wedding/location"><%= attending_dif %></a></li>
				  </ul>
				</div>
				</td>
				<td><%= link_to 'Edit', edit_invitee_path(@invitee) %></td>

		<% end %>
		</table>
	</div>
</div>


<%= link_to 'Back', invitees_path %>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Aanwezigheid</h4>
        </div>
        <div class="modal-body">
          Hier kun je aanpassen of je verwacht wel of niet te komen. Mocht dit later wijzigen, dan kan dit altijd nog. Maar het geeft een ons beeld hoeveel mensen er komen. Zo kunnen we rekening houden met bijvoorbeeld genoeg drankjes. 
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

<% @invitee.guests.each do |guest| %>
	<%= guest.name %>
<% end %>

app/views/layouts/_navigation.html.erb
<!-- Navigation -->
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <a href="/wedding" class="navbar-brand">De Bruiloft</a>
    <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse navHeaderCollapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="/pages/wedding/location">Locatie</a></li>
        <li><a href="/pages/wedding/ceremoniemeester">Ceremoniemeester</a></li>
        <li><a href="/invitees">Gasten</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Gast informatie<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="/wedding/fotos">Foto's</a></li>
            <li><a href="/wedding/kadotips">Kado tips</a></li>
            <li><a href="/hotels">Overnachten</a></li>
          </ul>
        </li>
        <li><a href="#">Contact</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wedding</title>
  <meta charset="utf-8">
  <meta name="wedding" content="">
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %> 
  <link href="/assets/bootstrap.css?body=1" media="screen" rel="stylesheet">

</head>




<body>
<div class="container">

<%= render '/layouts/navigation' %>

	<%= yield %>


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="/assets/bootstrap.min.js"></script>

</div>
</body>
</html>

app/views/location/index.html.erb
locatie

app/views/welcome/index.html.erb
<!-- Carousel -->

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
<!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
<!-- Wrapper for slides -->
<div class="carousel-inner">
<div class="item active">
  <%= image_tag 'welcome/champagne.png' %>
  <div class="carousel-caption">
    <h3></h3>
    <p></p>
  </div>
</div>
<div class="item">
  <%= image_tag 'welcome/camera.jpg' %>
  <div class="carousel-caption">
    <h3></h3>
    <p></p>
  </div>
</div>
<div class="item">
  <%= image_tag 'welcome/malediven.jpg' %>
  <div class="carousel-caption">
    <h1></h1>
    <p></p>
  </div>
</div>
</div>
<!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<!--Test met images-->
<!-- <div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="365" style="width:<%=@days_p%>%;">
    Dagen tot bruiloft: <%= @days_p %>
  </div>
</div> -->

<!--Test met images-->
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="thumbnail">
      <%= image_tag 'welcome/de_zwarte_boer.png' %>
        <div class="caption">
          <h3>De Zwarte Boer</h3>
          <p>In het pittoreske Leuvenum ligt midden in de bossen het kleinste 4 sterren hotel van Nederland.</p>
          <div class='text-center'>
          <p><a href="location" class="btn btn-primary" role="button" btn-pull-right>Meer info</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="thumbnail">
      <img src="http://www.letsgodigital.org/images/producten/340/specs/canon_eos_10d_front.jpg" alt="...">
        <div class="caption">
          <h3>Foto's</h3>
          <p>We zouden het leuk vinden als zoveel mogelijk mensen fotos maken. Neem je camera dus mee!</p>
          <div class='text-center'>
          <p><a href="location" class="btn btn-primary" role="button" btn-pull-right>Meer info</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="thumbnail">
      <img src="http://cdn.kveller.com/blog/wp-content/uploads/2011/11/Hanukkah-presents-300x200.jpg" alt="...">
        <div class="caption">
          <h3>Kado Tips</h3>
          <p>Wat willen we echt graag hebben. Kijk hier voor een lijstje van zaken die we graag ontvangen.</p>
          <div class='text-center'>
          <p><a href="location" class="btn btn-primary" role="button" btn-pull-right>Meer info</a></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-3">
      <div class="thumbnail">
      <img src="http://www.kontaktderkontinenten.nl/Images/Foto_kamers/hotelkamer-210_200x300_2910.aspx" alt="...">
        <div class="caption">
          <h3>Overnachten</h3>
          <p>Leuvenum is niet voor iedereen naast de deur. Hier enkele tips voor wie wil overnachten.</p>
          <div class='text-center'>
          <p><a href="location" class="btn btn-primary" role="button" btn-pull-right>Meer info</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>